project:
  type: website

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Finance"
        file: viz.qmd
      - text: "More"
        menu:
          - eod.qmd
          - about.qmd 
    right: 
      - about.qmd
  page-footer: "Copyright 2022, Lars Nygaard"


format:
  html:
    css: styles.css

editor: visual

