---
title: "Oversikt"
author: "MLars Nygaard"
abstract: "Financial Portal."
date: "`r Sys.Date()`"
output:
  html_document:
    self_contained: false 
    toc: true
    toc_depth: 2
    toc_float: true
    number_sections: true
params:
  year: 2018
  region: Europe
  printcode: TRUE
---

```{js, echo=FALSE}
$('.title').css('color', 'darkred')
```

```{r options, echo=FALSE, warning=FALSE, message=FALSE}
library(knitr)
Rpackage <- function (pkg) {sprintf("*%s*", pkg)}
CRANpkg <- function (pkg){
    cran <- "https://CRAN.R-project.org/package"
    fmt <- "[%s](%s=%s)"
    Rpackage(sprintf(fmt, pkg, cran, pkg))
}
library(googleVis)
options(prompt = "R> ", digits = 4, 
        show.signif.stars = FALSE,
        gvis.plot.tag='chart')
```

Hello, Website!

For more information about simple R Markdown websites, please read the documentation at https://bookdown.org/yihui/rmarkdown/rmarkdown-site.html.

Please also note that simple R Markdown sites are _not_ based on **blogdown**. They are probably good for websites with only a few Rmd documents. For larger-scale and more sophisticated websites (such as blogs), you may want to use **blogdown** instead: https://github.com/rstudio/blogdown.

<script src="javascript.js"></script>




# This is a plot
```{r, message=FALSE}
library(trelliscopejs)
library(ggplot2)
library(gapminder)
qplot(year, lifeExp, data = gapminder) +
  xlim(1948, 2011) + ylim(10, 95) + theme_bw() +
  facet_trelliscope(~ country + continent, nrow = 2, ncol = 7, width = 300, path = ".")
```

```{r}
print(params$year)
print(params$region)
print(params$printcode)
```

```{r demos, eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
library(googleVis)
op <- options(gvis.plot.tag='chart')

set.seed(2020)
x <- seq(0,100,by=0.5)
y <- (50-x)^2+rnorm(length(x),sd=100)
 
curvy <- data.frame(x,y)
 
 
gvScat <- gvisScatterChart(curvy,
                   options=list(
                     explorer="{actions: [‘dragToZoom’,
                     ‘rightClickToReset’],
                     maxZoomIn:0.05}",
                     chartArea="{width:’85%’,height:’80%’}",
                     hAxis="{title: ‘Explanatory x’,
                     titleTextStyle: {color: ‘#000000’}}",
                     vAxis="{title: ‘Response y’,
                     titleTextStyle: {color: ‘#000000’}}",
                     title="Curvilinear Relationship",
                     width=550, height=500,
                     legend="none"),
                   chartid="ZoomZoom")
 
plot(gvScat)
```

